map ctrl+shift+z new_tab
map ctrl+shift+x close_window
map ctrl+*        change_font_size all +2.0
map ctrl+minus           change_font_size all -2.0
map ctrl+kp_subtract     change_font_size all -2.0
