position = "bottom"
height = 24
margin.bottom = 6
margin.top = 3
margin.right = 6
margin.left = 6

[[start]]
type = "workspaces"


[[start]]
type = "launcher"
show_names = false
show_icons = true


[[end]]
type = "tray"
icon_size = 24


[[end]]
type = "clipboard"

[[end]]
type = "music"
#truncate = "end"
#truncate.length = 10
truncate.mode = "end"
truncate.max_length = 20

[[end]]
type = "volume"


[[end]]
type = "clock"
format = "  %H:%M:%S\n%d/%m/%Y"
justify = "center"

[[end]]
type = "notifications"
show_count = true
